version: '3.3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sad
      - MYSQL_DATABASE=sad
  olap:
    image: buggtb/saikuce:latest
    ports:
      - 8080:8080
    hostname: myhost
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1