
CREATE TABLE DIM_CUSTOMERS (
	ID_CUSTOMER INT(6),
	NAME VARCHAR(50),
	COUNTRY VARCHAR(50),
	CITY VARCHAR(50)
)

INSERT INTO DIM_CUSTOMERS(ID_CUSTOMER, NAME, COUNTRY, CITY)
SELECT C.id, C.first_name, C.country_region, C.city FROM customers C
SELECT * from sad.DIM_CUSTOMERS


CREATE TABLE DIM_PRODUCTS (
	ID_PRODUCT INT(6),
	NAME VARCHAR(50),
	SKU VARCHAR(50),
	CATEGORY VARCHAR(50)
)

INSERT INTO DIM_PRODUCTS(ID_PRODUCT, NAME, SKU, CATEGORY)
SELECT P.id, P.product_name, P.product_code, P.category FROM products P
SELECT * FROM DIM_PRODUCTS

CREATE TABLE DIM_TIME(
	YEAR INT(4),
	MONTH VARCHAR(30),
	DAY INT(2)
)

INSERT INTO DIM_TIME (YEAR, MONTH, DAY)
SELECT YEAR(O.order_date), MONTHNAME(O.order_date), DAY(O.order_date) FROM orders O
SELECT * FROM DIM_TIME


CREATE TABLE MEA_ORDERS (
	CUSTOMER_NAME VARCHAR(50),
	PRODUCT_NAME VARCHAR(50),
	PRODUCT_CATEGORY VARCHAR(50),
	PRODUCT_UNIT_PRICE DECIMAL(19,4),
	YEAR INT(4),
	MONTH VARCHAR(30),
	DAY INT(2)
)

INSERT INTO MEA_ORDERS(CUSTOMER_NAME, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_UNIT_PRICE, YEAR, MONTH, DAY)
SELECT C.first_name , P.product_name, P.category, OD.unit_price, YEAR(O.order_date), MONTHNAME(O.order_date), DAY(O.order_date) FROM orders O
INNER JOIN order_details OD ON O.id = OD.order_id
INNER JOIN products P ON OD.product_id = P.id
INNER JOIN customers C ON O.customer_id = C.id