
/** CUSTOMERS DIMENSION **/
CREATE TABLE DIM_CUSTOMERS (
	ID_CUSTOMER VARCHAR(5),
	NAME VARCHAR(50),
	COUNTRY VARCHAR(50),
	CITY VARCHAR(50)
)
/* LOAD */
INSERT INTO DIM_CUSTOMERS(ID_CUSTOMER, NAME, COUNTRY, CITY)
SELECT C.CustomerID, C.ContactName, C.Country, C.City FROM customers C
/* SELECT */
SELECT * from DIM_CUSTOMERS


/** PRODUCTS DIMENSION **/
CREATE TABLE DIM_PRODUCTS (
	ID_PRODUCT INT(11),
	NAME VARCHAR(50),
	CATEGORY VARCHAR(50)
)
/* LOAD */
INSERT INTO DIM_PRODUCTS(ID_PRODUCT, NAME, CATEGORY)
SELECT P.ProductID, P.ProductName, C.CategoryName
FROM products P
INNER JOIN categories C ON P.CategoryID = C.CategoryID
/* SELECT */
SELECT * FROM DIM_PRODUCTS

/** TIME DIMENSION **/
CREATE TABLE DIM_TIME(
	YEAR INT(4),
	MONTH VARCHAR(30),
	DAY INT(2)
)
/* LOAD */
INSERT INTO DIM_TIME (YEAR, MONTH, DAY)
SELECT YEAR(O.OrderDate), MONTHNAME(O.OrderDate), DAY(O.OrderDate) FROM orders O
/* SELECT */ 
SELECT * FROM DIM_TIME

/** ORDERS MEASURE **/
CREATE TABLE MEA_ORDERS (
	CUSTOMER_NAME VARCHAR(50),
	PRODUCT_NAME VARCHAR(50),
	PRODUCT_CATEGORY VARCHAR(50),
	PRODUCT_UNIT_PRICE DECIMAL(19,4),
	YEAR INT(4),
	MONTH VARCHAR(30),
	DAY INT(2)
)

/* LOAD */
INSERT INTO MEA_ORDERS(CUSTOMER_NAME, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_UNIT_PRICE, YEAR, MONTH, DAY)
SELECT C.ContactName , P.ProductName, CT.CategoryName, OD.UnitPrice , YEAR(O.OrderDate), MONTHNAME(O.OrderDate), DAY(O.OrderDate) FROM orders O
INNER JOIN `order details` OD ON O.OrderId = OD.OrderId
INNER JOIN products P ON OD.ProductId = P.ProductID
INNER JOIN categories CT ON P.CategoryID = CT.CategoryID
INNER JOIN customers C ON O.CustomerID = C.CustomerID
/*SELECT */
SELECT * FROM MEA_ORDERS
